# -*- coding: utf-8 -*-
'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89,⋯
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.'''
Ts = raw_input('')
T = int(Ts)
caseN = list()
for i in range(T):
    caseN.append(long(raw_input('')))
for N in caseN:
    fib1 = 1
    fib2 = 1
    fib3 = 1
    evenSum = 0
    x = 2
    while x < N + 1:
        fib3 = fib1 + fib2
        fib1 = fib2
        fib2 = fib3            
        x = x + 1        
        if (x%3==0 and fib3 < N):
            evenSum = evenSum + fib3
        elif fib3 > N:
            break
    print evenSum 